// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Question struct {
	ID       int64
	Question string
	Answer   sql.NullString
}

type Quiz struct {
	ID          int64
	Title       string
	QuestionIds []int64
}
